---
# tasks file for docker-elastic
- hosts: docker
  tasks:
        - name: Create a elastic container
          docker_container:
            name: elastic
            image: elasticsearch:7.4.2
            state: started
            recreate: yes
            exposed_ports:
            - '9200:9200'
            - '9300:9300'
            volumes:
            - /etc/elasticsearch/:/home/challenge/conf/
            - /var/lib/elasticsearch/data/:/home/challenge/data/
            - /var/lib/elasticsearch/logs/:/home/challenge/logs/
        - name: Copiando configuracion
          become: true
          template:
                src: "elasticsearch.yml.j2"
                dest: "/home/challenge/conf/elasticsearch.yml"
                owner: root
                group: root
                mode: '0644'
                backup: yes
        - name: open ports tcp
          firewalld:
            port: 9200/tcp
            source: 192.168.0.0/24
            zone: public
            immediate: yes
            permanent: yes
            state: enabled
        - name: open udp
          firewalld:
            port: 9200/udp
            source: 192.168.0.0/24
            zone: public
            immediate: yes
            permanent: yes
            state: enabled
        - name: open ports tcp
          firewalld:
            port: 9300/tcp
            source: 192.168.0.0/24
            zone: public
            immediate: yes
            permanent: yes
            state: enabled
        - name: open udp
          firewalld:
            port: 9300/udp
            source: 192.168.0.0/24
            zone: public
            immediate: yes
            permanent: yes
            state: enabled
        - name: restartd firewalld
          service: 
                name: firewalld 
                state: restarted