---
# tasks file for docker-kibana
- hosts: docker
  tasks:
        - name: Create a kibana container
          docker_container:
            name: kibana
            image: kibana:7.4.2
            state: started
            recreate: yes
            exposed_ports:
              - "5601:5601"
            volumes:
              - /home/challenge/conf/kibana:/usr/share/kibana/config/kibana.yml
            links: "elastic:elasticsearch"
        - name: Copiando configuracion
          become: true
          template:
                src: "kibana.yml.j2"
                dest: "/home/challenge/conf/kibana.yml"
                owner: root
                group: root
                mode: '0644'
                backup: yes
        - name: open ports tcp
          firewalld:
            port: 5601/tcp
            source: 192.168.0.0/24
            zone: public
            immediate: yes
            permanent: yes
            state: enabled
        - name: open udp
          firewalld:
            port: 5601/udp
            source: 192.168.0.0/24
            zone: public
            immediate: yes
            permanent: yes
            state: enabled
        - name: restartd firewalld
          service: 
                name: firewalld 
                state: restarted